version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .               
      dockerfile: backend/Dockerfile 
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: ./frontend     
      dockerfile: Dockerfile   
    container_name: frontend
    ports:
      - "5713:5713"
    depends_on:
      - backend

volumes:
  mongo-data:
